### ISSUE TITLE
support `--limit 10` option for command `forge block 1...20`

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/forge-cli#12]
## Motivation

When there are too many data, forge-cli should limit max amount to display.

## Proposal

- add `--limit <number>` option for `forge block` command;
- do proper truncate for parsed block height array;
- prompt user with a `symbols.warning` that the result is truncated;

**Comment by mave99a** [comment]
how about support pause. 

in command line word, pause and hit space to next screen was pretty common at the time.

sort of: 

ls | more

**Comment by polunzh** [comment]
Not necessary, closed.
