### ISSUE TITLE
download simulator/workshop/swap service on first usage

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/forge-cli#128]
Since simulator workshop and swap service are not core components of forge, we should not download it before user actually starting to use it.

The initial assets to download should include: forge/forge_web, when user first runs `forge simulator start`, forge-cli should be smart enough to figure out that the corresponding forge simulator has been downloaded or not, then download it before actually run it.

This works very similar to forge protocil:compile, which users forge-compiler internally.

**Comment by mave99a** [comment]
This should be covered by the new design which decouple forge-core, forge-web, forge-cli etc. 

everything will be a blocklet, downloadable and installable. 

close this issue since it will be a dup with others
