### ISSUE TITLE
Proposal: list, remove created chains

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-cli#133]
We now have `forge create-chain`, then we should have: 

- list-chain: list all created chains
- remove-chain: remove a created chain

**Comment by wangshijun** [comment]
For subcommand naming consistency, we should name commands like this:

- `forge chain:create`
- `forge chain:ls`
- `forge chain:remove`

**Comment by polunzh** [comment]
Current:

![img](https://user-images.githubusercontent.com/4244426/62934260-ae933c00-bdf6-11e9-89b8-a6d33ad85571.png)
