### ISSUE TITLE
Should not always ask user to  add a new customize config for a chain during install especially if there is already chain defined. 

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-cli#137]
Should not always ask user to  add a new customize config for a chain during install.  Especially if there is already chain defined. 

Right now after `forge install` it will always ask to config a new or default chain despite there are chains defined already.   We should check if there is existing chain, if none, then ask if user want create a default chain. otherwise a user may create many times. 

```
$ forge install latest
ℹ Detected platform is: darwin
✔ Latest forge release version: v0.36.4

...

? Do you want to customize config for this chain? No
Now you can start a forge node with forge start
```

**Comment by wangshijun** [comment]
implementation logic: if `~/.forge_chains` is not empty, do not prompt user to config after install.

add prompt to use `forge config set`
