### ISSUE TITLE
proposal: consider adopt truffle box idea to improve create app from starter projects

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-cli#154]
proposal: consider adopt truffle box idea to improve create app from starter projects

This Truffle Box concept is pretty good.  It’s essentially our “xxxx-starter” project concept.

The different is, it provide a quick way for users to use it, by add it to command line:
`truffle unbox box-project-name`
So for every box project, it just need 2 lines to get started:
`npm install -g truffle`
`truffle unbox box-project-name`
I think our starter projects are already very close to this, except we ask user to run `npm install xxx-starter` for themselves
I think we can learn from them for this part? @shijun @Matt M
They also allow users contribute Boxes, which is good, it’s managed manually by sending them emails.
so far they have quite a few “boxes”: https://www.trufflesuite.com/boxes

**Comment by wangshijun** [comment]
close since our blocklet site is live and `forge blocklet:use` does not require preinstall of an blocklet.
