### ISSUE TITLE
Manage a list of starter template with a git repo, and be able to display all available starter templates

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-cli#162]
Manage a list of starter template with a git repo, and be able to display all available starter templates. 

This is related to our inspiration from “Truffle Boxes”.  

First step: we can list all existing starter templates 

Second step: we can use a git repo to manage the list of the available starter templates.

**Comment by wangshijun** [comment]
close this because our blocklet site is live: https://blocklet.arcblock.io
