### ISSUE TITLE
proposal: `forge protocol:create` to create a template of a new protocol

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-cli#164]
`forge protocol:create` to create a template of a new protocol.

**Comment by wangshijun** [comment]
Let's rename protocol => contract before v1.0 release

**Comment by wangshijun** [comment]
https://github.com/ArcBlock/forge-core-protocols/blob/master/lib/trade/exchange/config.yml

**Comment by polunzh** [comment]
TODO:
1. [x] rename protocol => contract before v1.0 release
2. [x] add `contract:create` command
