### ISSUE TITLE
`forge project:create` hang for a while and no output

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-cli#165]
version CLI v0.37.1 . `forge project:create` hang for me and do nothing, no output.

looks like it's doing something, just taking long time. so if the parameter is correct it finally will prompt the directory, if not correct it will display after a while. 

We Should prompt what we are doing don't let user feel it's hang

**Comment by polunzh** [comment]
Before create project, cli will do a network request to fetch all starters information, it may block the flow.
I added a loading effect.

**Comment by polunzh** [comment]
![image](https://user-images.githubusercontent.com/4244426/63408927-b0768400-c422-11e9-8650-90cd2e5473cf.png)
