### ISSUE TITLE
in `forge status`  should print all endpoints that application can use

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-cli#168]
in `forge status`  should print all endpoints that application can use, right now there is no place to display those important information for developer to use. 

I have a related issue for forgeweb, since on forge web developer may also need to find those information:
https://github.com/ArcBlock/forge-web/issues/124

**Comment by polunzh** [comment]
@mave99a 
Latest update will print endpoints in `forge status` and `forge ps`.

![](https://user-images.githubusercontent.com/4244426/63496471-8f7e6380-c4f4-11e9-83d9-3ca7b44dfaa9.png)
![](https://user-images.githubusercontent.com/4244426/63496491-9d33e900-c4f4-11e9-9e43-824a78e2f1c3.png)
