### ISSUE TITLE
support custom config by a config file when create a chain

### ISSUE THREAD

**Issue by polunzh** [ArcBlock/forge-cli#172]
And some commands should support --yes param for automation:

1. forge chain:create
1. forge config

**Comment by wangshijun** [comment]
@polunzh we should make `--config-path` work again to support this feature, forge-cli can accept arbitary valid config file path to start a new chain.

**Comment by polunzh** [comment]
> @polunzh we should make `--config-path` work again to support this feature, forge-cli can accept arbitary valid config file path to start a new chain.

OK
