### ISSUE TITLE
add faq in the repo and documentation site

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/forge-cli#20]
- How to update forge-cli
- How to debug when `forge start` failed
- How to solve `node-grpc` build error issue
- How to cleanup an existing install
- How to check latest version

**Comment by mave99a** [comment]
How to clean uninstall forge, and a prompt to developer to check if they have old version

**Comment by wangshijun** [comment]
#30

**Comment by wangshijun** [comment]
https://github.com/arcblock/forge-cli/blob/HEAD/docs/FAQ.md
