### ISSUE TITLE
forge-cli won't work for ansible

### ISSUE THREAD

**Issue by tyrchen** [ArcBlock/forge-cli#243]
For ansible task:

```
- name: 'install forge {{ forge_version }}'
  shell: 'forge install {{ forge_version }} --silent'
```

many times this won't install forge successfully, while no error is reported. Previously we thought this is an issue for the old forge cli, but it seems the latest forge cli has this issue.

**Comment by polunzh** [comment]
Install via script failed probably caused by version checking, which blocked the installation.
#246

**Comment by polunzh** [comment]
> and the weird thing is that if the forge is already started do a 'forge start' again would exit already started forge. This also happened on ansible script.
> 
> ```
> fatal: [10.2.86.115]: FAILED! => {"changed": true, "cmd": "forge start", "delta": "0:00:44.125370", "end": "2019-09-24 21:20:24.968068", "msg": "non-zero return code", "rc": 1, "start": "2019-09-24 21:19:40.842698", "stderr": "- Waiting for chain default to start...\n✖ Forge cannot be successfully started, now exiting...\n- Waiting for chain default to stop...", "stderr_lines": ["- Waiting for chain default to start...", "✖ Forge cannot be successfully started, now exiting...", "- Waiting for chain default to stop..."], "stdout": "\n✖ Forge start failed: forge is not started within 40 seconds\nℹ Stopping default chain...\n\n✖ kill EPERM\n✖ cannot get daemon process info, ensure forge is started!\n\nℹ Possible solutions:\n──────────────\n1. Cleanup already running forge\nEnsure no running forge process that cannot be detected by forge-cli\nRun: forge stop default, to stop forge related processes, then try forge start default again\n\n2. Report bug to our engineer\nIt is very likely that forge cannot be started on your environment\nPlease run: forge start default --dry-run", "stdout_lines": ["", "✖ Forge start failed: forge is not started within 40 seconds", "ℹ Stopping default chain...", "", "✖ kill EPERM", "✖ cannot get daemon process info, ensure forge is started!", "", "ℹ Possible solutions:", "──────────────", "1. Cleanup already running forge", "Ensure no running forge process that cannot be detected by forge-cli", "Run: forge stop default, to stop forge related processes, then try forge start default again", "", "2. Report bug to our engineer", "It is very likely that forge cannot be started on your environment", "Please run: forge start default --dry-run"]}
> ```

如果执行 forge start 失败的话，cli会主动退出该条链所有相关的进程。
但是重复执行 forge start 的话 cli 确实有bug，因为这个时候cli的进程的exit code不等于0，这个bug已经提了PR了:
https://github.com/ArcBlock/forge-cli/pull/249

**Comment by polunzh** [comment]
> > and the weird thing is that if the forge is already started do a 'forge start' again would exit already started forge. This also happened on ansible script.
> > ```
> > fatal: [10.2.86.115]: FAILED! => {"changed": true, "cmd": "forge start", "delta": "0:00:44.125370", "end": "2019-09-24 21:20:24.968068", "msg": "non-zero return code", "rc": 1, "start": "2019-09-24 21:19:40.842698", "stderr": "- Waiting for chain default to start...\n✖ Forge cannot be successfully started, now exiting...\n- Waiting for chain default to stop...", "stderr_lines": ["- Waiting for chain default to start...", "✖ Forge cannot be successfully started, now exiting...", "- Waiting for chain default to stop..."], "stdout": "\n✖ Forge start failed: forge is not started within 40 seconds\nℹ Stopping default chain...\n\n✖ kill EPERM\n✖ cannot get daemon process info, ensure forge is started!\n\nℹ Possible solutions:\n──────────────\n1. Cleanup already running forge\nEnsure no running forge process that cannot be detected by forge-cli\nRun: forge stop default, to stop forge related processes, then try forge start default again\n\n2. Report bug to our engineer\nIt is very likely that forge cannot be started on your environment\nPlease run: forge start default --dry-run", "stdout_lines": ["", "✖ Forge start failed: forge is not started within 40 seconds", "ℹ Stopping default chain...", "", "✖ kill EPERM", "✖ cannot get daemon process info, ensure forge is started!", "", "ℹ Possible solutions:", "──────────────", "1. Cleanup already running forge", "Ensure no running forge process that cannot be detected by forge-cli", "Run: forge stop default, to stop forge related processes, then try forge start default again", "", "2. Report bug to our engineer", "It is very likely that forge cannot be started on your environment", "Please run: forge start default --dry-run"]}
> > ```
> 
> 如果执行 forge start 失败的话，cli会主动退出该条链所有相关的进程。
> 但是重复执行 forge start 的话 cli 确实有bug，因为这个时候cli的进程的exit code不等于0，这个bug已经提了PR了:
> #249

这个PR已经发布了。但是这修复只是修复了CLI在重复执行时进程退出码的bug，但是这个bug和你贴的错误日志并没有直接关系，而是forge start自身的问题。我没能复现这个bug，你那边如果能复现的话，能提供一下详细的配置和日志吗？
