### ISSUE TITLE
`forge install latest` returns invalid version

### ISSUE THREAD

**Issue by rileyshu53** [ArcBlock/forge-cli#256]
## Reproduce

With a fresh forge-cli `0.39.0`, if type `forge install latest`, it shows an error `Invalid Version: latest`. `forge install` is working.

## Problem
However, the second line of the screenshot it prompts user to use `forge install latest`.
If we don't support `latest` as a version, we should remove this in the previous prompt.

<img width="649" alt="Screen Shot 2019-09-30 at 11 23 35 AM" src="https://user-images.githubusercontent.com/40574465/65905175-eb9a9a00-e374-11e9-9430-bf5ee9dcd50a.png">

**Comment by wangshijun** [comment]
fixed in v0.39.1
