### ISSUE TITLE
Graphql playground shows no document supplied error

### ISSUE THREAD

**Issue by magrook** [ArcBlock/forge-cli#272]
My command line sequence of events:

forge@craig-backbone:~/.forge_chains$ forge web stop
ℹ Stopping forge web...

forge@craig-backbone:~/.forge_chains$ forge web start
ℹ forge web already started.

forge@craig-backbone:~/.forge_chains$ forge web open --graphql
ℹ forge web not started yet
✔ Forge web successfully started
ℹ forge web running at:     http://localhost:8210
ℹ graphql endpoint at:      http://localhost:8210/api
Opening http://localhost:8210/api/playground...

Upon opening this address in my browser, I am met with:

`{"errors":[{"message":"No query document supplied"}]}`

**Comment by wangshijun** [comment]
@polunzh this issue is caused by forge-cli itsself.

**Comment by wangshijun** [comment]
More context of this issue: tutorial followed is: https://www.arcblock.io/en/post/2019/10/06/getting-started-with-forge

**Comment by polunzh** [comment]
This may be caused by CLI not stop Forge Web successfully, I fixed the issue in:
https://github.com/ArcBlock/forge-cli/commit/785eb6716b097176cbb9cbde936993480036fbbc#diff-27500fee70e72aeaeed81183614584f4R50
