### ISSUE TITLE
ABT Chain Node crashing

### ISSUE THREAD

**Issue by magrook** [ArcBlock/forge-cli#288]
## Describe the bug

ABT Chain Node starts, but crashes due to missing folders and permissions errors

## To Reproduce

1. cd /usr/local/bin/abtchainnode
2. execute abtchainnode
3. See attached screenshot for output

## Expected behavior

The application to start for further experimentation

## Screenshots

![Screenshot from 2019-10-15 15-05-47](https://user-images.githubusercontent.com/15899796/66873658-d8372380-ef5d-11e9-862b-c32601c570e9.png)

## Desktop (please complete the following information):

- OS: Debian 9
- forge-cli: 0.39.13

## Additional context

Additionally it would be handy to be able to copypaste the error message in the error dialog box (instead of pasting a screenshot).

**Comment by polunzh** [comment]
ABT Chain Node had been deprecated.
Closed.
