### ISSUE TITLE
It's harder to use since new CLI always require user to have `-c default` in parameters

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-cli#290]
e.g. 

```
forge version
✖ chainName argument is required

```

I only want to see what's software versions.

**Comment by polunzh** [comment]
Solved.
`chainName` is no longer required.
> If `chainName` is not provide, CLI would get first running chain.
> If there was no running chains, CLI would get first chain of existed
> chains. And if there was no chains existed, CLI would exit.
