### ISSUE TITLE
forge start failed

### ISSUE THREAD

**Issue by PaperHS** [ArcBlock/forge-cli#314]
## Forge start failed 

![image](https://user-images.githubusercontent.com/4629442/67835899-1f104600-fb26-11e9-878f-cf4122076a1b.png)

forge start failed with error hint

## To Reproduce

1. Create 3 account
2. delegate A to C
3. create a asset for B
4. make exchange A and B with delegator C.
5. forge crash out
6. forge restart failed

## Desktop (please complete the following information):

- OS: Mac
- forge-cli: 0.39.11

**Comment by PaperHS** [comment]
我想知道的是：如何不删除数据从错误状态中恢复过来

**Comment by polunzh** [comment]
@PaperHS CLI 优化了在启动的时候启动forge失败的检查。
