### ISSUE TITLE
[UI] Improvement for create chain an upgrade

### ISSUE THREAD

**Issue by polunzh** [ArcBlock/forge-cli#322]
- [ ] <del>tendermint -> consensus, maybe add a `consensus` description is better</del>: keep tendermint
- [ ] load remote available forge releases when upgrade
- [x] block time default value: 3s
- [x] `token icon` unnecessary when create chain
- [ ] <del>if `token` is editable when create chain</del> hide this option 
- [x] feel lucky -> checkin bonus
- [x] moderator -> admin chain
- [x] initial token holder balance description (why 35B)
- [x] print `partial configs` when config chain
- [x] initial capitalization of outputs
- [x] remove help list after installed, instead, just print `install/chain:create/start` hints

**Comment by polunzh** [comment]
## Others
1. make `Arcblock` logo looks better when config
1. rename moniker? I don't think is feasibility
1. connect did, is this a feature?
1. remote `cpu` column from process stats outputs?
1. make upgrade more effective

**Comment by wangshijun** [comment]
close because we have a new issue to track the todo that's not finished yet.
