### ISSUE TITLE
[Next release] Major goal of next release is simplify forge-cli and move some into the web interface

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-cli#362]
Major goal of next release is simplify forge-cli and move some into the web interface. 

**Principles**: 

Those should remain in CLI: 

- Commands need to be executed from time to time
- Commands that likely be used in a **script** for test automation, deployment, etc. 
- Commands that input and outputs are super simple (e.g. version) 
- Commands that the output may be used to generate into files for automatic processing

Those should move to web:

- Commands that only need to use for few times (e.g. initialization, configuration) 
- Commands that need many inputs or user interaction (e.g. config, create assets etc) 

---

My vision of future forge cli use is just a few command line: 

```
$ npm install arcblock-framework                 # install everything,  start it
Installing...
Starting ArcBlock at http://localhost:8080/...
$
```

or something even less dependency, just start from a download and run a script: 

```
$curl https://install.arcblock.com/ | sh
Downloading...
Installing...
Starting ArcBlock at http://localhost:8080/...
```

Just remember our original vision is always something like `Wordpress` install process.  We want to build a blockchain node super easy to get started. command line is cool, but it stops a lot of people.  I think in the past we over-invested in forge-cli and make it over complex, we should totally move things into web interface from next release.

**Comment by mave99a** [comment]
Related to @jonathanlu813

**Comment by wangshijun** [comment]
let's close this in favor of https://github.com/ArcBlock/abt-node/issues/17
