### ISSUE TITLE
One web interface, allow web based switch to any local chain endpoint 

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-cli#370]
One web interface, allow web based switch to any local chain endpoint, should not use the local storage, since user may need multi-tab on browser to monitor each chain. 

this will become available when we decouple forge-webapp from forge-web, and support switchable endpoint. 

related to: https://github.com/ArcBlock/forge-webapp/issues/231

**Comment by wangshijun** [comment]
https://github.com/ArcBlock/forge-cli/issues/370

**Comment by mave99a** [comment]
对现有的一些命令行这样处理： 

`forge web start` `forge web stop` `forge web open --graphql` 不再必要，总是有web的。GQL Playground总是提供的（原来的为什么还要提供简陋版 playground，我没理解？ forge webapp里有豪华版了）。

`forge web open` 还是保留的，就是打开浏览器并指向到我们的web服务。 如果参数里带了链的id，就切到该链 （因此**链的选择是可以在url里传入**的， 这个要注意。 过去放在local storage里并不适合，因为用户可能需要开多个tab，分别在不同链上操作）

我们的web服务的首页，并不设计为现在的forge web，而是一个专门的index 页面， 第一个版本这里可以是空的，或者只是一个简单的帮助说明文字。 以后这个首页，是链的列表，和其他系列功能（包括第一次安装的开始的地方），通过这里，我们一步步实现未来从web 引导用户安装、配置的全过程。

**Comment by wangshijun** [comment]
already landed
