### ISSUE TITLE
forge init is ambiguous

### ISSUE THREAD

**Issue by polunzh** [ArcBlock/forge-cli#45]
`forge init` means to init something, mybe run only once, I think `forge install` is better.

**Comment by wangshijun** [comment]
Let's make this command default to `install` and use `init` as an alias

**Comment by wangshijun** [comment]
![Screen Shot 2019-07-08 at 09 34 52](https://user-images.githubusercontent.com/719985/60777214-c0cceb00-a163-11e9-87a0-d2888e042ea0.png)
