### ISSUE TITLE
forge react starter project need add "shelljs" package

### ISSUE THREAD

**Issue by NateRobinson** [ArcBlock/forge-cli#65]
![屏幕快照 2019-07-05 下午5 42 09](https://user-images.githubusercontent.com/12446758/60713762-3c544f80-9f4c-11e9-979e-c558515116b4.png)

**Comment by wangshijun** [comment]
fixed in https://github.com/ArcBlock/forge-dapp-starters/commit/3736525e1ea0f75e0bb8d7063a51e7b55afc0f6e
