### ISSUE TITLE
Support signing any transaction from the CLI 

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-cli#7]
This is related to #97 

Support signing from the CLI,  so when a developer need to debug wallet related apps, or hardware wallet, they can use CLI to  sign a transaction (not broadcast it) for testing purpose. 

The CLI can: 

1. Generate a not signed version TX

2. Sign the TX (not broadcast)

3. Send the was TX (broadcast signed tx)

With this 3 feature, debuting wallet app will be easier

**Comment by wangshijun** [comment]
@mave99a  this feature can be added when node.js version `mcrypto` is ready, since we will produce a signature that can be verified by forge-core from outside forge-core, we need both client and web sdk ready for offline tx signing.

**Comment by polunzh** [comment]
Not necessary, Closed. @wangshijun
