### ISSUE TITLE
proposal: red Arcblock logo feels like exception happens

### ISSUE THREAD

**Issue by polunzh** [ArcBlock/forge-cli#70]
![image](https://user-images.githubusercontent.com/4244426/60715033-b1c11f80-9f4e-11e9-934c-4e013edf860d.png)

**Comment by wangshijun** [comment]
let's change it to blue `#4E6AF6`

**Comment by wangshijun** [comment]
![Screen Shot 2019-07-08 at 10 34 27](https://user-images.githubusercontent.com/719985/60779082-fc6bb300-a16b-11e9-885d-fbc841fecb58.png)
