### ISSUE TITLE
Can we have a test automation for check all supported command line in an environment ?

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/forge-cli#8]
Can we have a test automation for check all supported command line in an environment ?

**Comment by wangshijun** [comment]
@mave99a this can be done by analyzing all subcommand requirements and the current env, then list commands that can be run at current env

**Comment by polunzh** [comment]
@wangshijun Maybe we should also test on supported OS platforms.

**Comment by mave99a** [comment]
not a priority since we'll going to move to a more web friendly design. close
