### ISSUE TITLE
forge web not running on http://localhost:8210/

### ISSUE THREAD

**Issue by echoecho-arcblock** [ArcBlock/forge-cli#80]
after run `forge web open`
![image](https://user-images.githubusercontent.com/52221874/60919234-15e32c80-a24a-11e9-822b-ffb158f698cf.png)

if it needs to remove previous forge version and re-do the steps, we need to show it off

**Comment by echoecho-arcblock** [comment]
under Boshan's help,
I  went on running `forge status` -> `forge` -> `forge web start`, then it works

**Comment by polunzh** [comment]
I added graphql service check before web started successfully, there would be some error display if the check failed.

**Comment by polunzh** [comment]
@echoecho-arcblock 
The latest version fixed the bug, if still can't start web, just try one more time.
If there any questions or bug, please tell us.
