### ISSUE TITLE
status error

### ISSUE THREAD

**Issue by robroyhobbs** [ArcBlock/forge-cli#81]
after starting forge, running through commands including forge status and received an error message.  not sure if this is the same as error 61.  
<img width="841" alt="forge status error" src="https://user-images.githubusercontent.com/41485426/60919525-d1a45c00-a24a-11e9-91f6-a8747805a9a2.png">

**Comment by sunboshan** [comment]
This bug probably is the same issue as `bin/forge_starter pid` returns rpc error. Will take a deeper look at this issue on the erlang side.

**Comment by wangshijun** [comment]
@robroyhobbs Very likely that you have a chain state with an older version of forge, but you started a new version of forge against the old state, if that's the case, forge will crash after start.

**Comment by robroyhobbs** [comment]
I’m simply following the documentation and directions. Nowhere does it say I have to remove previous versions, etc.  if it is an error i run into then likely someone else will do the same in the future.

**Comment by polunzh** [comment]
#92

**Comment by wangshijun** [comment]
#114

**Comment by wangshijun** [comment]
latest forge-cli will exit when forge start failed
